
DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	tenant_id BIGINT(20) NOT NULL COMMENT 'ID',
	name VARCHAR(255) NULL DEFAULT NULL COMMENT '名称',
	age VARCHAR (255) NULL DEFAULT NULL COMMENT '年龄',
	birthday DATE  NULL DEFAULT NULL COMMENT '生日',
	headshot VARCHAR (255) NULL DEFAULT NULL COMMENT '头像',
	signature VARCHAR (255) NULL DEFAULT NULL COMMENT '个性签名',
	nickname VARCHAR(255) NULL DEFAULT NULL COMMENT '昵称',
	phone VARCHAR(255) NULL DEFAULT NULL COMMENT '手机号',
	role INT(11) NULL DEFAULT NULL COMMENT '角色',
	love INT(11) NULL DEFAULT NULL COMMENT '喜欢',
	focus INT(11) NULL DEFAULT NULL COMMENT '关注',
	article_sum INT(11) NULL DEFAULT NULL COMMENT '文章数量',
	address VARCHAR(255) NULL DEFAULT NULL COMMENT '籍贯',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS article;

/*文章表*/
CREATE TABLE article
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
	tenant_id BIGINT(20) NOT NULL COMMENT 'ID',
	title VARCHAR(255) NULL DEFAULT NULL COMMENT '标题',
	content TEXT NULL DEFAULT NULL COMMENT '内容',
	date DATE  NULL DEFAULT NULL COMMENT '发表日期',
	article_type INT(11) NULL DEFAULT NULL COMMENT '文章类型',
	recommend INT(11) NULL DEFAULT NULL COMMENT '推荐',
	user INT(11) NULL DEFAULT NULL COMMENT '发表用户',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS comments;

/*评论*/
CREATE TABLE comments
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
	tenant_id BIGINT(20) NOT NULL COMMENT 'ID',
	content TEXT NULL DEFAULT NULL COMMENT '评论内容',
	user INT(11) NULL DEFAULT NULL COMMENT '用户',
	article INT(11) NULL DEFAULT NULL COMMENT '文章',
	date DATE NULL DEFAULT NULL COMMENT '评论日期',
	praise INT(11) NULL DEFAULT NULL COMMENT '赞数',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS reply;

CREATE TABLE reply
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
	tenant_id BIGINT(20) NOT NULL COMMENT 'ID',
	article INT(11) NULL DEFAULT NULL COMMENT '评论内容',
	parent_id INT(11) NULL DEFAULT NULL COMMENT '父评论',
	child_id INT(11) NULL DEFAULT NULL COMMENT '子评论',
	PRIMARY KEY (id)
);


DROP TABLE IF EXISTS photos;

CREATE TABLE photos
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
	tenant_id BIGINT(20) NOT NULL COMMENT 'ID',
	url INT(11) NULL DEFAULT NULL COMMENT 'uri',
	article INT(11) NULL DEFAULT NULL COMMENT '文章',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS video;

CREATE TABLE video
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
	tenant_id BIGINT(20) NOT NULL COMMENT 'ID',
	url INT(11) NULL DEFAULT NULL COMMENT 'uri',
	article INT(11) NULL DEFAULT NULL COMMENT '文章',
	PRIMARY KEY (id)
);



